---
# Configure your freshly installed software
- hosts: all
  roles:

  - role: temporary-folder
    create_temp_dir: true
    delete_temp_dir: false

  - role: repository
    git_repos:
      dotfiles:
        clone_url: https://github.com/mateusrevoredo/dotfiles
        dest: "{{ dotfiles }}"
      powerline:
        clone_url: https://github.com/powerline/fonts.git
        dest: "{{tempdir.stdout}}/powerline"

  - role: zsh
    osx_login_shell: /usr/local/bin/zsh

  - role: filesystem
    # Dotfiles to be symlinked in any other folder
    custom_links:
      # sublime:
      #   source: "sublime"
      #   destination: "/Users/{{ ansible_user_id }}/Library/Application\ Support/Sublime\ Text\ 3/Packages/User"
      # karabiner-customization:
      #   source: "karabiner/private.xml"
      #   destination: "/Users/{{ ansible_user_id }}/Library/Application\ Support/Karabiner/private.xml"
      karabiner-preferences:
        source: "karabiner/org.pqrs.Karabiner.plist"
        destination: "/Users/{{ ansible_user_id }}/Library/Preferences/org.pqrs.Karabiner.plist"
      seil:
        source: "seil/org.pqrs.Seil.plist"
        destination: "/Users/{{ ansible_user_id }}/Library/Preferences/org.pqrs.Seil.plist"
      vlc:
        source: "vlc"
        destination: "/Users/{{ ansible_user_id }}/Library/Preferences/org.videolan.vlc"
      day-o:
        source: "day-o/com.shauninman.Day-O.plist"
        destination: "/Users/{{ ansible_user_id }}/Library/Preferences/com.shauninman.Day-O.plist"
      iterm2:
        source: "iterm2/com.googlecode.iterm2.plist"
        destination: "/Users/{{ ansible_user_id }}/Library/Preferences/com.googlecode.iterm2.plist"
      skim:
        source: "skim/net.sourceforge.skim-app.skim.plist"
        destination: "/Users/{{ ansible_user_id }}/Library/Preferences/net.sourceforge.skim-app.skim.plist"
    # Dotfiles to be symlinked in the home directory ~/
    regular_dotfiles:
      zsh:
        source: "zsh/zshconfig"
        destination: ".zsh"
      vimrc:
        source: "vimrc"
        destination: ".vimrc"
      vim:
        source: "vim"
        destination: ".vim"
      tmux:
        source: "tmux.conf"
        destination: ".tmux.conf"
      lolcommits:
        source: "lolcommits"
        destination: ".lolcommits"
      slate:
        source: "slate"
        destination: ".slate"
      zshrc:
        source: "zshrc"
        destination: ".zshrc"
      # ohmyzshcustom:
      #   source: "zsh/oh-my-zsh/custom"
      #   destination: ".oh-my-zsh/custom"
      zgen:
        source: "zgen"
        destination: ".zgen"
      gitconfig:
        source: "gitconfig"
        destination: ".gitconfig"
      gitignoreglobal:
        source: "gitignore_global"
        destination: ".gitignore_global"
      gittemplates:
        source: "git-templates"
        destination: ".git-templates"

  - role: general

  - role: temporary-folder
    create_temp_dir: false
    delete_temp_dir: true
