---
- name: Tap the repositories
  homebrew_tap: "tap={{ item }}"
  with_items: brew_taps

- name: Install the homebrew packages
  homebrew: name={{ item }} state=latest
  with_items: brew_packages

- name: Install the cask packages
  homebrew_cask: name={{ item }}
  environment:
    HOMEBREW_CASK_OPTS: --appdir={{ brew_cask_caskroom }} --binarydir={{ brew_cask_binarydir }}
  with_items: cask_packages

- name: Install homebrew package(s) with brew options
  homebrew: name={{ item.pkg }} install_options={{ item.opts }} state={{ item.state|default("latest") }}
  with_items: brew_pkg_with_opts
  when: brew_pkg_with_opts is defined

- name: Install ruby gems
  gem: name={{ item }} state=latest
  with_items: ruby_gems