---
- name: assert cask presence
  stat: path={{ install_dir }}/bin/brew-cask.rb
  register: cask_installed

- name: tap the cask repository
  homebrew_tap: tap=caskroom/cask state=present
  when: cask_installed.stat.exists == false

- name: install brew-cask
  homebrew: name=brew-cask state=latest update_homebrew=yes
  when: cask_installed.stat.exists == false
